### ISSUE TITLE
New signature types for cashier model

### ISSUE THREAD

**Issue by dimaloop** [deniskristov/checkbox-api-client#1]
There are updated new Signature Types for Cashier:

[https://dev-api.checkbox.in.ua/api/redoc#operation/get_cashier_profile_api_v1_cashier_me_get](https://dev-api.checkbox.in.ua/api/redoc#operation/get_cashier_profile_api_v1_cashier_me_get)

- AGENT
- UKEY
- DEPOSITSIGN
- SMARTSIGN
- CLOUD_SIGNATURE
- CLOUD_SIGNATURE_2
- TEST

Can they be added to SIGNATURE_TYPE enum?

Currently I've get deserialization exception on TEST and CLOUD_SIGNATURE_2 signatures

Thanks

**Comment by deniskristov** [comment]
Thanks for your comment. Fixed in v. 1.10.4
