### ISSUE TITLE
/goods endpoint

### ISSUE THREAD

**Issue by dimaloop** [deniskristov/checkbox-api-client#3]
Is it possible to add search goods with /goods endpoint?

[https://dev-api.checkbox.in.ua/api/redoc#operation/get_goods_api_v1_goods_get](https://dev-api.checkbox.in.ua/api/redoc#operation/get_goods_api_v1_goods_get)

for some unknown reason, the method /good/{id} is works only with uuid identifiers and for searching by CRM code is needs to fetch goods with search by code. The only one method in API - /goods endpoint with "query" parameter (api docs are little bit poor for this point, it is unclear if the search by product code works)

Perhaps I am missing some part of the workflow, but it is unclear where else I can take UUID of goods to sell they with a ReceiptSellPayload

Thank you so much for your assistance!

**Comment by deniskristov** [comment]
I've added ```/goods``` endpoint with ```query``` 
This query search all goods that contain ```query``` in any GoodModel's field
The idea of this endpoint is to find any product matching a string without specifying a concrete field (e.g in a mobile app).

**Comment by dimaloop** [comment]
Thank you, Denis!

There is only one question left in my mind - why checkbox does not have any method for updating goods, but this question is not relevant to this wrapper....

Thank you again for great job!
WBR,
Dmytro

**Comment by deniskristov** [comment]
Thank you, Dmytro!

**Comment by JrooTJunior** [comment]
This questions are not related with this API wrapper but i'm (as developer of checkbox) can answers some of them.

> for some unknown reason, the method /good/{id} is works only with uuid identifiers

Because the only id is unique but name, code or barcode is not.

> Perhaps I am missing some part of the workflow, but it is unclear where else I can take UUID of goods to sell they with a ReceiptSellPayload

If you already use a different goods accounting system and only wants to create receipts via API you don't need to create goods on checkbox side and fill the `good_id` field, this field is optional and now used only on web-portal and mobile application.

> There is only one question left in my mind - why checkbox does not have any method for updating goods, but this question is not relevant to this wrapper....

In the near future it will be possible to create goods and use goods accounting via API (leftover, supply, etc.) since a few weeks ago we announced a new goods accounting system: https://t.me/checkbox_info/41

Now this system is already enabled for all users, which means soon you can create new goods via API or mobile application in the same way as it just possible on web-portal.

**Comment by dimaloop** [comment]
Thank you for reply!

Is it possible to not save goods in checkbox's "inventory", when we create receipt via API?
Just simply point name, code, price and quantity which are required?

.. and since there is an opportunity to ask a question to the developer directly, tell me please - what is the purpose of the **barcode** field on receipt sell POST endpoint?
[https://dev-api.checkbox.in.ua/api/redoc#operation/create_receipt_api_v1_receipts_sell_post](https://dev-api.checkbox.in.ua/api/redoc#operation/create_receipt_api_v1_receipts_sell_post)

is it barcode of receipt? or what? thank you)

**Comment by deniskristov** [comment]
> Is it possible to not save goods in checkbox's "inventory", when we create receipt via API?
Just simply point name, code, price and quantity which are required?

Yes, that is the way I create receipts.

**Comment by JrooTJunior** [comment]
> Is it possible to not save goods in checkbox's "inventory", when we create receipt via API?
> Just simply point name, code, price and quantity which are required?

Yes, you can create receipts without registration of the nomenclature of goods and pass all goods data to the receipts API.
The `good_id` field is needed only for registering leftovers in the goods accounting system.

> what is the purpose of the **barcode** field on receipt sell POST endpoint? 
> is it barcode of receipt?

Yep, that's barcode of receipt.
Is placed below receipt totals and service information.
![image](https://user-images.githubusercontent.com/6726423/149167688-e1ef1e24-6742-4624-a8f7-fa0db98b74d4.png)

**Comment by dimaloop** [comment]
@JrooTJunior, thank you for a such detailed example !

**Comment by dimaloop** [comment]
If i want to insert item code before item's title string - can i use barcode field for that purpose? Because good's code not printed on receipt

**Comment by JrooTJunior** [comment]
Yes
Or you can use header field of goods

**Comment by dimaloop** [comment]
@JrooTJunior, sorry for off-topic
but I cannot get answer from checkbox support..

Is there a way to change paper size for [receipt pdf](https://dev-api.checkbox.in.ua/api/redoc#operation/get_receipt_pdf_api_v1_receipts__receipt_id__pdf_get) ? 
We use thermo printers with 80 mm paper width but your pdf is use only A4 dimension
