### ISSUE TITLE
Extending getShifts with parameters [pr]

### ISSUE THREAD

**Issue by dimaloop** [deniskristov/checkbox-api-client#5]
Currently method getShifts() doesn't use any parameters, so api defaults used
so, not possible to query other than first page

parameters list [from api docs](https://dev-api.checkbox.in.ua/api/redoc#operation/get_shifts_api_v1_shifts_get):

statuses | Array of any (ShiftStatus) Enum: "CREATED" "OPENING" "OPENED" "CLOSING" "CLOSED"
-- | --
desc | boolean (Desc)Default: false, Зворотній порядок сортування
limit | integer (Limit) [0 .. 1000], Default: 25
offset | integer (Offset) >= 0, Default: 0

Perhaps it makes sense to introduce an object ShiftsFilter and pass them as argument to getShifts(ShiftsFilter filter)

**Comment by deniskristov** [comment]
I've just added ShiftsFilter
